version: '3.9'

services:
  db:
    image: postgres
    env_file: resvy/docker-test.env
    tmpfs:
      - /var/lib/postgresql/data:rw

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d test_db" ]
      interval: 1s
      timeout: 5s
      retries: 5
  webapp:
    container_name: application
    build: ""
    env_file: resvy/docker-test.env
    entrypoint: ./coverage.sh
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
