version: '3.9'

services:
  db:
    image: postgres
    tmpfs:
      - /var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=resvy_db
      - POSTGRES_USER=resvy
      - POSTGRES_PASSWORD=resvy
    volumes:
      - cache:/cache
      - build:/build
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U resvy -d resvy_db" ]
      interval: 1s
      timeout: 5s
      retries: 5
  webapp:
    build: .
    ports:
      - "8000:8000"
    entrypoint: ["bash", "entrypoint.sh"]
    command:
      - uvicorn
      - resvy.asgi:application
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
    environment:
      - POSTGRES_NAME=resvy_db
      - POSTGRES_USER=resvy
      - POSTGRES_PASSWORD=resvy
      - DB_HOST=db
      - REDIS_ENABLED=1
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  redis:
    image: redis:alpine

volumes:
  cache:
    external: true
  build:
    external: true
