# Generated by Django 4.0.4 on 2022-04-13 18:09

from django.db import migrations, models
import django.db.models.deletion
import reservations.utils


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_assign_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'permissions': (('can_manage_tables', 'Can manage Tables'),)},
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[reservations.utils.present_or_future_date], verbose_name='Reservation Date')),
                ('from_time', models.TimeField(validators=[reservations.utils.present_or_future_time], verbose_name='From time')),
                ('to_time', models.TimeField(validators=[reservations.utils.present_or_future_time], verbose_name='To time')),
                ('persons', models.PositiveSmallIntegerField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.table', verbose_name='Table')),
            ],
            options={
                'ordering': ['date', 'from_time'],
                'permissions': (('can_manage_reservation', 'Can manage reservation'),),
                'unique_together': {('date', 'from_time', 'to_time')},
            },
        ),
    ]
